### ISSUE TITLE
Email counter broken

### ISSUE THREAD

**Issue by lukem512** [des-des/train-strike#2]
<img width="305" alt="screen shot 2017-07-31 at 09 03 59" src="https://user-images.githubusercontent.com/2834976/28768349-376fbf8e-75cf-11e7-9d5b-49f6b9b9ad30.png">

No errors on the command line but the email counter no longer updates.

**Comment by des-des** [comment]
Fixed on my local functions file had been wiped so was not getting deployed but now up
